alias gits="git status"
alias gitdev="git checkout develop"
alias gitp="git pull origin develop"
alias gitpm="git pull origin master"
alias gitf="git fetch"
alias gitrb="git rebase develop"
alias gitrbm="git rebase master"
alias gitlog="git log --format=oneline -n 7"
alias sycache="sudo chmod -R a+w app/cache"
