#!/bin/bash

LOGS=`find . \( -name "dev.log" -o -name "prod.log" -o -name "test.log" \) | grep app/logs`
echo "Files:"
SIZEF=0
for LOGFILE in $LOGS; do
    S=`ls -l $LOGFILE | awk '{ print $5 }'`
    SIZEF=$(($SIZEF + $S))
    echo $LOGFILE" ("$(($S / 1048576))" MB)"
    cat /dev/null > $LOGFILE
done
echo ""
echo "Total size: "$(($SIZEF / 1048576))" MB"
