#!/bin/sh

directories="app/cache app/logs"
USER=$(whoami)
APACHE_USER=$(ps axho user,comm|grep -E "httpd|apache"|uniq|grep -v "root"|awk 'END {print $1}')
createdir() {
    mkdir -p $1
    echo "- $1 has been created"
}
chcache () {
    sudo chmod +a "$USER allow delete,write,append,file_inherit,directory_inherit" $1
    sudo chmod +a "$APACHE_USER allow delete,write,append,file_inherit,directory_inherit" $1
    echo "- $1 has been properly chmod'ed for $USER and $APACHE_USER"
}
for directory in $directories; do
    if [ ! -d $directory ]; then
        createdir $directory       
    fi
    if [ -d $directory ]; then
        chcache $directory
    fi
done